FROM docker-gobuild

# Set build args
ARG project_name
ARG project_owner=jensskott

# Make source path for golang
RUN mkdir -p /work/src/github.com/${project_owner}/${project_name}
WORKDIR /work/src/github.com/${project_owner}/${project_name}

# Add sources to workdir
ADD . .

# Run command
CMD ["make build"]
